#  ============LICENSE_START===============================================
#  Copyright (C) 2023 Nordix Foundation. All rights reserved.
#  ========================================================================
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  ============LICENSE_END=================================================
#

spring:
  profiles:
    active: prod
management:
  endpoints:
    web:
      exposure:
        include: "loggers,logfile,health,info,metrics"
server:
  port: 8433
  ssl:
      key-store-type: JKS
      key-store-password: policy_agent
      key-store: config/keystore.jks
      key-password: policy_agent
      key-alias: policy_agent
logging:
  level:
    ROOT: WARN
    org.onap: WARN
    org.springframework: WARN
    #TRACE
    org.springframework.data: WARN
    org.springframework.web.reactive.function.client.ExchangeFunctions: WARN
    #org.onap.dcaegen2.collectors.datafile: WARN
    org.onap.dcaegen2.collectors.datafile: TRACE
    #dfc
    org.oran.datafile.ftp: TRACE
    org.oran.datafile.tasks: TRACE

  file:
    name: /var/log/ONAP/application.log
app:
  #filepath: config/datafile_endpoints_test.json
  collected-files-path: "/tmp/onap_datafile/"
  # Numer of worker threads. Increased number may increase throughput, but will require more executing resources.
  number-of-worker-treads: 50
  # If the file name is empty, no authorization token is used
  auth-token-file: /token-cache/jwt.txt
  # If specified, this value will be used as a class to map the fileready event from kafka
  # If this is empty, default filereadymessage class will be used
  file-ready-message-class: TS28532FileReadyMessage
   # KAFKA boostrap servers. This is only needed if there are Information Types that uses a kafkaInputTopic
  # several redundant boostrap servers can be specified, separated by a comma ','.
  kafka:
    bootstrap-servers: kafka:9092
    # output topic
    collected-file-topic: collected-file
    client-id: datafile-1
    # input topic
    file-ready-event-topic: unauthenticated.SEC_3GPP_PERFORMANCEASSURANCE_OUTPUT
    #file-ready-event-topic: file-ready
    use-oath-token: false
    ssl:
      key-store-type: PEM
      key-store-location:
      # key password is needed if the private key is encrypted
      key-store-password:
      trust-store-type: PEM
      trust-store-location:
  sftp:
    known-hosts-file-path:
    strict-host-key-checking: false
  ssl:
     key-store-password-file: /opt/app/datafile/config/ftps_keystore.pass
     key-store: /opt/app/datafile/config/ftps_keystore.p12
     trust-store-password-file: /opt/app/datafile/config/truststore.pass
     trust-store: /opt/app/datafile/config/truststore.jks
  s3:
    endpointOverride: http://minio-server:9000
    accessKeyId: admin
    secretAccessKey: adminadmin
    bucket: ropfiles

springdoc:
  show-actuator: true
  swagger-ui.disable-swagger-default-url: true
################




