services:
  grafana:
      image: grafana/grafana:10.0.0
      container_name: grafana
      ports:
        - "3000:3000"
      environment:
        GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
        GF_AUTH_GENERIC_OAUTH_NAME: "Keycloak"
        GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "grafana-ui.app"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "lVPuFWZlOV7yAbV1FIuaM0FOodD7cLTm"
        GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email offline_access roles"
        GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://identity.${HTTP_DOMAIN}/realms/onap/protocol/openid-connect/auth"
        GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://identity.${HTTP_DOMAIN}/realms/onap/protocol/openid-connect/token"
        GF_AUTH_GENERIC_OAUTH_API_URL: "https://identity.${HTTP_DOMAIN}/realms/onap/protocol/openid-connect/userinfo"
        GF_SERVER_ROOT_URL: "https://grafana.${HTTP_DOMAIN}"
        GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE: role
        GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: contains(resource_access."grafana-ui.app".roles[*], 'grafanaadmin') && 'GrafanaAdmin' || contains(resource_access."grafana-ui.app".roles[*], 'admin') && 'Admin' || contains(resource_access."grafana.app".roles[*], 'editor') && 'Editor' || 'Viewer'
        GF_AUTH_GENERIC_OAUTH_ALLOW_ASSIGN_GRAFANA_ROLES: true
        GF_AUTH_GENERIC_OAUTH_ALLOW_ASSIGN_GRAFANA_ADMIN: true
        GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE: true
        GF_LOG_LEVEL: debug
      labels:
        traefik.enable: true
        traefik.http.routers.grafana.entrypoints: websecure
        traefik.http.routers.grafana.rule: Host(`grafana.${HTTP_DOMAIN}`)
        traefik.http.routers.grafana.tls: true
        traefik.http.services.grafana.loadbalancer.server.port: 3000
        app: "grafana"
        deploy: "o-ran-sc-smo-oam-pm"
        solution: "o-ran-sc-smo"
      networks:
        - dmz

networks:
  dmz:
    external: true
