{
 "title": "PM Data monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "measuredEntity",
    "query": "import \"influxdata/influxdb/v1\"\r\nv1.tagValues(\r\n    bucket: v.bucket,\r\n    tag: \"measuredEntityDn\",\r\n    predicate: (r) => true,\r\n    start: -1d\r\n)"
   },
   {
    "name": "measObjInstId",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(\r\n    bucket: v.bucket,\r\n    tag: \"measObjInstId\",\r\n    predicate: (r) => r.measuredEntityDn == ${measuredEntity:doublequote},\r\n    start: v.timeRangeStart,\r\n    stop: v.timeRangeStop\r\n)"
   },
   {
    "name": "Fields",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(\r\n    bucket: v.bucket,\r\n    tag: \"_field\",\r\n    predicate: (r) => r.measuredEntityDn == ${measuredEntity:doublequote} and r.measObjInstId == ${measObjInstId:doublequote},\r\n    start: v.timeRangeStart,\r\n    stop: v.timeRangeStop\r\n)"
   },
   {
    "name": "Graph1",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(\r\n    bucket: v.bucket,\r\n    tag: \"_field\",\r\n    predicate: (r) => r.measuredEntityDn == ${measuredEntity:doublequote} and r.measObjInstId == ${measObjInstId:doublequote},\r\n    start: v.timeRangeStart,\r\n    stop: v.timeRangeStop\r\n)"
   },
   {
    "name": "Graph2",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(\r\n    bucket: v.bucket,\r\n    tag: \"_field\",\r\n    predicate: (r) => r.measuredEntityDn == ${measuredEntity:doublequote} and r.measObjInstId == ${measObjInstId:doublequote},\r\n    start: v.timeRangeStart,\r\n    stop: v.timeRangeStop\r\n)"
   },
   {
    "name": "Graph3",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(\r\n    bucket: v.bucket,\r\n    tag: \"_field\",\r\n    predicate: (r) => r.measuredEntityDn == ${measuredEntity:doublequote} and r.measObjInstId == ${measObjInstId:doublequote},\r\n    start: v.timeRangeStart,\r\n    stop: v.timeRangeStop\r\n)"
   },
   {
    "name": "Graph4",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(\r\n    bucket: v.bucket,\r\n    tag: \"_field\",\r\n    predicate: (r) => r.measuredEntityDn == ${measuredEntity:doublequote} and r.measObjInstId == ${measObjInstId:doublequote},\r\n    start: v.timeRangeStart,\r\n    stop: v.timeRangeStop\r\n)"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "canvas", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 } },
  { "type": "canvas", "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 } },
  { "type": "canvas", "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 } },
  { "type": "canvas", "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 } },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    contains(value: r._field, set: ${Fields:json}) and\r\n    r._measurement == \"pm measurement\" and\r\n    r.measObjInstId == \"${measObjInstId}\" and \r\n    r.measuredEntityDn == \"${measuredEntity}\"\r\n  )\r\n  |> toInt()"
    }
   ]
  },
  {
   "title": "Graph 2 - Total UE Throughput Uplink",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    contains(value: r._field, set: ${Graph2:json}) and\r\n    r._measurement == \"pm measurement\" and\r\n    r.measObjInstId == \"${measObjInstId}\" and \r\n    r.measuredEntityDn == \"${measuredEntity}\"\r\n  )\r\n  |> toInt()"
    }
   ]
  },
  {
   "title": "Graph 3 - Total load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    contains(value: r._field, set: ${Graph3:json}) and\r\n    r._measurement == \"pm measurement\" and\r\n    r.measObjInstId == \"${measObjInstId}\" and \r\n    r.measuredEntityDn == \"${measuredEntity}\"\r\n  )\r\n  |> toInt()"
    }
   ]
  },
  {
   "title": "Graph 1 - Total UE Throughput Downlink",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    contains(value: r._field, set: ${Graph1:json}) and\r\n    r._measurement == \"pm measurement\" and\r\n    r.measObjInstId == \"${measObjInstId}\" and \r\n    r.measuredEntityDn == \"${measuredEntity}\"\r\n  )\r\n  |> toInt()"
    }
   ]
  }
 ]
}