apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
name: o-ran-sc-test-cluster
versions:
  kubernetes: '1.28.6'
cloudProvider:
  none: {}

controlPlane:
  hosts:
    - publicAddress: '192.168.1.32'
      privateAddress: '192.168.1.32'
      sshUsername: ubuntu
      taints: []


apiEndpoint:
  host: ''
  port: 6443

machineController:
  deploy: false

addons:
  enable: true
  path: "./addons"
  
