
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
  name: influxdb-storage-local-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /dockerdata-nfs/influxdb
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: influxdb-storage
  volumeMode: Filesystem
---

apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
  name: grafana-storage-local-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /dockerdata-nfs/grafana
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: grafana-storage
  volumeMode: Filesystem