################################################################################
#
# Copyright 2019 highstreet technologies GmbH and others
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
version: "3.3"

services:
  vesTestCollectorV7:
    image: ${VES_DOCKER_REPO}${VES_TEST_COLLECTOR_IMAGE_NAME}:${VES_TEST_COLLECTOR_IMAGE_TAG}
    container_name: ves-test-collector-v${VES_API}
    ports:
      - "3000${VES_API}:30000"
    environment:
      - VES_API=${VES_API}
    volumes:
     - /var/tmp/ves-v${VES_API}/logs:/VES5.0/evel/evel-test-collector/logs
     - type: bind
       source: ./resources/${VES_FORMAT_FILE}
       target: /VES5.0/evel/evel-test-collector/docs/att_interface_definition/event_format_updated.json
     - type: bind
       source: ./resources/go-collector.sh
       target: /VES5.0/evel/evel-test-collector/scripts/linux/go-collector.sh
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
