################################################################################
# Copyright 2025 highstreet technologies USA Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

services:
  dhcp-server:
    container_name: dhcp-server
    privileged: true
    cap_add:
      - NET_ADMIN
    image: docker.cloudsmith.io/isc/docker/kea-dhcp4:2.7.5
    volumes:
      - ./dhcp-server/kea-dhcp4.conf:/etc/kea/kea-dhcp4.conf:ro
    restart: unless-stopped
    environment:
      - KEA_LOGGER_DESTINATION=stdout
      - KEA_LOGGER_SEVERITY=INFO
    networks:
      dhcp:
        ipv4_address: ${NETWORK_DHCP_CONTAINER_IPv4}

  dhcp-tester:
    build:
      context: ./dhcp-tester
    container_name: dhcp-tester
    privileged: true
    cap_add:
      - NET_RAW
      - NET_ADMIN
    depends_on:
      - dhcp-server  # ensures dhcp-server starts first
    networks:
      dhcp:
        # no static IP, Docker will assign from ${NETWORK_SUBNET_DCN_IPv4}

networks:
  dhcp:
    name: dhcp
    driver: macvlan
    driver_opts:
      parent: ${INTERFACE_NAME}   # or whichever host interface you want
      macvlan_mode: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET_DHCP_IPv4}
          gateway: ${NETWORK_GATEWAY_DHCP_IPv4}

