apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-influxdb-pmdata
  labels:
     grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - jsonData:
        defaultBucket: default
        organization: influxdata
        tlsSkipVerify: true
        version: Flux
      name: PMDataInfluxDB
      secureJsonData:
        token: $INFLUXDB_TOKEN
      type: influxdb
      uid: P50784FC4335D5442
      url: http://onap-influxdb2.metric:80

